/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import clases.Gato;
import clases.PlayWave;
import java.net.URISyntaxException;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Miguel
 */
public class FrmTablero extends javax.swing.JFrame {
    
    private FrmIntro frmIntro;
    private FrmAcercaDe frmAcerca = new FrmAcercaDe();
    private Gato gato;
    private JLabel[] tablero;
    private boolean banOk = false;        //  <------------------
    private boolean banInicio;  
    private boolean primerTiro;

    /**
     * Creates new form FrmTablero
     */
    public FrmTablero() {
        initComponents();
        setLocationRelativeTo(null);
        gato = new Gato();
        tablero = new JLabel[9];
        tablero[0] = lblImagen1;
        tablero[1] = lblImagen2;
        tablero[2] = lblImagen3;
        tablero[3] = lblImagen4;
        tablero[4] = lblImagen5;
        tablero[5] = lblImagen6;
        tablero[6] = lblImagen7;
        tablero[7] = lblImagen8;
        tablero[8] = lblImagen9;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblImagen1 = new javax.swing.JLabel();
        lblImagen2 = new javax.swing.JLabel();
        lblImagen3 = new javax.swing.JLabel();
        lblImagen4 = new javax.swing.JLabel();
        lblImagen5 = new javax.swing.JLabel();
        lblImagen6 = new javax.swing.JLabel();
        lblImagen7 = new javax.swing.JLabel();
        lblImagen8 = new javax.swing.JLabel();
        lblImagen9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblTirador = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnAcercaDe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juego del Gato V 1.2");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Juego del Gato");

        lblImagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gato_pics/vacia.png"))); // NOI18N
        lblImagen1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblImagen1.setEnabled(false);
        lblImagen1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen1MouseClicked(evt);
            }
        });

        lblImagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gato_pics/vacia.png"))); // NOI18N
        lblImagen2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblImagen2.setEnabled(false);
        lblImagen2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen2MouseClicked(evt);
            }
        });

        lblImagen3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gato_pics/vacia.png"))); // NOI18N
        lblImagen3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblImagen3.setEnabled(false);
        lblImagen3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen3MouseClicked(evt);
            }
        });

        lblImagen4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gato_pics/vacia.png"))); // NOI18N
        lblImagen4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblImagen4.setEnabled(false);
        lblImagen4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen4MouseClicked(evt);
            }
        });

        lblImagen5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gato_pics/vacia.png"))); // NOI18N
        lblImagen5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblImagen5.setEnabled(false);
        lblImagen5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen5MouseClicked(evt);
            }
        });

        lblImagen6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gato_pics/vacia.png"))); // NOI18N
        lblImagen6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblImagen6.setEnabled(false);
        lblImagen6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen6MouseClicked(evt);
            }
        });

        lblImagen7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gato_pics/vacia.png"))); // NOI18N
        lblImagen7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblImagen7.setEnabled(false);
        lblImagen7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen7MouseClicked(evt);
            }
        });

        lblImagen8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gato_pics/vacia.png"))); // NOI18N
        lblImagen8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblImagen8.setEnabled(false);
        lblImagen8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen8MouseClicked(evt);
            }
        });

        lblImagen9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gato_pics/vacia.png"))); // NOI18N
        lblImagen9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblImagen9.setEnabled(false);
        lblImagen9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen9MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Tirador:");

        lblTirador.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTirador.setForeground(new java.awt.Color(255, 0, 0));

        btnRegistrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnNuevo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setEnabled(false);
        btnNuevo.setFocusCycleRoot(true);
        btnNuevo.setFocusPainted(false);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gato_pics/cerrar-ventana-icono-5596-16.png"))); // NOI18N
        btnSalir.setToolTipText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnAcercaDe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAcercaDe.setText("Acerca de..");
        btnAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcercaDeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblImagen7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblImagen8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblImagen9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblImagen4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblImagen5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblImagen6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblImagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblImagen3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(lblTirador, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 31, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(btnAcercaDe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalir)
                    .addComponent(btnAcercaDe))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(lblTirador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImagen3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImagen4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImagen5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImagen6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImagen7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImagen8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImagen9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnNuevo))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        banInicio = false;
        primerTiro=false;
        lblImagen1.setIcon(new ImageIcon(getClass().getResource("/gato_pics/vacia.png")));
        banInicio = true;
        if (banOk = false) {
            for (int i = 0; i < 9; i++) {
                tablero[i].setIcon(
                        new ImageIcon(getClass().getResource("/gato_pics/vacia.png")));
            }
        } else {
            banOk = true;
            for (int i = 0; i < 9; i++) {
                tablero[i].setIcon(
                        new ImageIcon(getClass().getResource("/gato_pics/vacia.png")));
            }
        }
        ocultar();
        frmIntro = new FrmIntro(gato);
        frmIntro.setVisible(true);

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        lblTirador.setText(gato.getJugador1());
    }//GEN-LAST:event_formWindowActivated

    private void lblImagen1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen1MouseClicked
        // TODO add your handling code here:
        if (gato.isBanInicio()) {
            tirar(0);
        }
    }//GEN-LAST:event_lblImagen1MouseClicked

    private void lblImagen2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen2MouseClicked
        // TODO add your handling code here:
        if (gato.isBanInicio()) {
            tirar(1);
        }
    }//GEN-LAST:event_lblImagen2MouseClicked

    private void lblImagen3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen3MouseClicked
        // TODO add your handling code here:
        if (gato.isBanInicio()) {
            tirar(2);
        }
    }//GEN-LAST:event_lblImagen3MouseClicked

    private void lblImagen4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen4MouseClicked
        // TODO add your handling code here:
        if (gato.isBanInicio()) {
            tirar(3);
        }
    }//GEN-LAST:event_lblImagen4MouseClicked

    private void lblImagen5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen5MouseClicked
        // TODO add your handling code here:
        if (gato.isBanInicio()) {
            tirar(4);
        }
    }//GEN-LAST:event_lblImagen5MouseClicked

    private void lblImagen6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen6MouseClicked
        // TODO add your handling code here:
        if (gato.isBanInicio()) {
            tirar(5);
        }
    }//GEN-LAST:event_lblImagen6MouseClicked

    private void lblImagen7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen7MouseClicked
        // TODO add your handling code here:
        if (gato.isBanInicio()) {
            tirar(6);
        }
    }//GEN-LAST:event_lblImagen7MouseClicked

    private void lblImagen8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen8MouseClicked
        // TODO add your handling code here:
        if (gato.isBanInicio()) {
            tirar(7);
        }
    }//GEN-LAST:event_lblImagen8MouseClicked

    private void lblImagen9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen9MouseClicked
        // TODO add your handling code here:
        if (gato.isBanInicio()) {
            tirar(8);
        }
    }//GEN-LAST:event_lblImagen9MouseClicked

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        musicaFondo();
        for (int i = 0; i < 9; i++) {
            tablero[i].setIcon(
                    new ImageIcon(getClass().getResource("/gato_pics/vacia.png")));
        }
        gato.reiniciar();
        banInicio = true;
        primerTiro= true;
        
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        int resp = JOptionPane.showConfirmDialog(null, "¿Realmente desea salir?");
        if (JOptionPane.OK_OPTION == resp) {
            System.exit(0);
        } else {
            
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcercaDeActionPerformed
        // TODO add your handling code here:  
        frmAcerca.setVisible(true);
    }//GEN-LAST:event_btnAcercaDeActionPerformed
    
    private void ocultar() {
        lblImagen1.setEnabled(true);
        lblImagen2.setEnabled(true);
        lblImagen3.setEnabled(true);
        lblImagen4.setEnabled(true);
        lblImagen5.setEnabled(true);
        lblImagen6.setEnabled(true);
        lblImagen7.setEnabled(true);
        lblImagen8.setEnabled(true);
        lblImagen9.setEnabled(true);
        btnNuevo.setEnabled(true);
        banOk = false;
    }
    
    private void tirar(int pos) {
        if (gato.ganador() == 0 && gato.getTiros() < 9) {
            gato.setTiro(pos);      //<------

            if (gato.isTurnoJ1()) {
                if (gato.getTiroJ1() == 1) {// Equis
                    tablero[pos].setIcon(new ImageIcon(
                            getClass().getResource("/gato_pics/equis.png")));
                } else {
                    tablero[pos].setIcon(new ImageIcon(
                            getClass().getResource("/gato_pics/cero.png")));
                }
            } else {
                if (gato.getTiroJ2() == 1) {// Equis
                    tablero[pos].setIcon(new ImageIcon(
                            getClass().getResource("/gato_pics/equis.png")));
                } else {
                    tablero[pos].setIcon(new ImageIcon(
                            getClass().getResource("/gato_pics/cero.png")));
                }
            }
            if (gato.ganador() != 0) {
                JOptionPane.showMessageDialog(this, "Ganó "
                        + lblTirador.getText() + "!!");
            } else if (gato.esEmpate()) {
                JOptionPane.showMessageDialog(this, "Es empate!!");
            } else {
                gato.cambiarTurno();
                if (gato.isTurnoJ1()) {
                    lblTirador.setText(gato.getJugador1());
                } else {
                    lblTirador.setText(gato.getJugador2());
                }
            }
        }
        switch (gato.ganador()) {
            case 0:
                if (gato.esEmpate()) {
                    JOptionPane.showMessageDialog(this, "Es empate!!");
                }
                break;
            case 1:     //Fila #1
                if (gato.isTurnoJ1()) {
                    if (gato.getTiroJ1() == 1) {
                        tablero[0].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_h.png")));
                        tablero[1].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_h.png")));
                        tablero[2].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_h.png")));
                    } else {
                        tablero[0].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_h.png")));
                        tablero[1].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_h.png")));
                        tablero[2].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_h.png")));
                    }
                } else {
                    if (gato.getTiroJ1() == 2) {
                        tablero[0].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_h.png")));
                        tablero[1].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_h.png")));
                        tablero[2].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_h.png")));
                    } else {
                        tablero[0].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_h.png")));
                        tablero[1].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_h.png")));
                        tablero[2].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_h.png")));
                    }
                }
                break;
            case 2:     //Fila #1
                if (gato.isTurnoJ1()) {
                    if (gato.getTiroJ1() == 1) {
                        tablero[3].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_h.png")));
                        tablero[4].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_h.png")));
                        tablero[5].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_h.png")));
                    } else {
                        tablero[3].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_h.png")));
                        tablero[4].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_h.png")));
                        tablero[5].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_h.png")));
                    }
                } else {
                    if (gato.getTiroJ1() == 2) {
                        tablero[3].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_h.png")));
                        tablero[4].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_h.png")));
                        tablero[5].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_h.png")));
                    } else {
                        tablero[3].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_h.png")));
                        tablero[4].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_h.png")));
                        tablero[5].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_h.png")));
                    }
                }
                break;
            case 3:     //Fila #1
                if (gato.isTurnoJ1()) {
                    if (gato.getTiroJ1() == 1) {
                        tablero[6].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_h.png")));
                        tablero[7].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_h.png")));
                        tablero[8].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_h.png")));
                    } else {
                        tablero[6].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_h.png")));
                        tablero[7].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_h.png")));
                        tablero[8].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_h.png")));
                    }
                } else {
                    if (gato.getTiroJ1() == 2) {
                        tablero[6].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_h.png")));
                        tablero[7].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_h.png")));
                        tablero[8].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_h.png")));
                    } else {
                        tablero[6].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_h.png")));
                        tablero[7].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_h.png")));
                        tablero[8].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_h.png")));
                    }
                }
                break;
            case 4:     //Fila #1
                if (gato.isTurnoJ1()) {
                    if (gato.getTiroJ1() == 1) {
                        tablero[0].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_v.png")));
                        tablero[3].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_v.png")));
                        tablero[6].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_v.png")));
                    } else {
                        tablero[0].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_v.png")));
                        tablero[3].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_v.png")));
                        tablero[6].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_v.png")));
                    }
                } else {
                    if (gato.getTiroJ1() == 2) {
                        tablero[0].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_v.png")));
                        tablero[3].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_v.png")));
                        tablero[6].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_v.png")));
                    } else {
                        tablero[0].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_v.png")));
                        tablero[3].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_v.png")));
                        tablero[6].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_v.png")));
                    }
                }
                break;
            case 5:     //Fila #1
                if (gato.isTurnoJ1()) {
                    if (gato.getTiroJ1() == 1) {
                        tablero[1].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_v.png")));
                        tablero[4].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_v.png")));
                        tablero[7].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_v.png")));
                    } else {
                        tablero[1].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_v.png")));
                        tablero[4].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_v.png")));
                        tablero[7].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_v.png")));
                    }
                } else {
                    if (gato.getTiroJ1() == 2) {
                        tablero[1].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_v.png")));
                        tablero[4].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_v.png")));
                        tablero[7].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_v.png")));
                    } else {
                        tablero[1].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_v.png")));
                        tablero[4].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_v.png")));
                        tablero[7].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_v.png")));
                    }
                }
                break;
            case 6:     //Fila #1
                if (gato.isTurnoJ1()) {
                    if (gato.getTiroJ1() == 1) {
                        tablero[2].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_v.png")));
                        tablero[5].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_v.png")));
                        tablero[8].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_v.png")));
                    } else {
                        tablero[2].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_v.png")));
                        tablero[5].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_v.png")));
                        tablero[8].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_v.png")));
                    }
                } else {
                    if (gato.getTiroJ1() == 2) {
                        tablero[2].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_v.png")));
                        tablero[5].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_v.png")));
                        tablero[8].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_v.png")));
                    } else {
                        tablero[2].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_v.png")));
                        tablero[5].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_v.png")));
                        tablero[8].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_v.png")));
                    }
                }
                break;
            case 7:     //Fila #1
                if (gato.isTurnoJ1()) {
                    if (gato.getTiroJ1() == 1) {
                        tablero[0].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_d1.png")));
                        tablero[4].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_d1.png")));
                        tablero[8].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_d1.png")));
                    } else {
                        tablero[0].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_d1.png")));
                        tablero[4].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_d1.png")));
                        tablero[8].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_d1.png")));
                    }
                } else {
                    if (gato.getTiroJ1() == 2) {
                        tablero[0].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_d1.png")));
                        tablero[4].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_d1.png")));
                        tablero[8].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_d1.png")));
                    } else {
                        tablero[0].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_d1.png")));
                        tablero[4].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_d1.png")));
                        tablero[8].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_d1.png")));
                    }
                }
                break;
            case 8:     //Diagonal #2
                if (gato.isTurnoJ1()) {
                    if (gato.getTiroJ1() == 1) {
                        tablero[2].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_d2.png")));
                        tablero[4].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_d2.png")));
                        tablero[6].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_d2.png")));
                    } else {
                        tablero[2].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_d2.png")));
                        tablero[4].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_d2.png")));
                        tablero[6].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_d2.png")));
                    }
                } else {
                    if (gato.getTiroJ1() == 2) {
                        tablero[2].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_d2.png")));
                        tablero[4].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_d2.png")));
                        tablero[6].setIcon(new ImageIcon(getClass().getResource("/gato_pics/equis_d2.png")));
                    } else {
                        tablero[2].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_d2.png")));
                        tablero[4].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_d2.png")));
                        tablero[6].setIcon(new ImageIcon(getClass().getResource("/gato_pics/cero_d2.png")));
                    }
                }
        }
    }
    
    public void musicaFondo() {
        try {
            PlayWave pw1;
            URL url = getClass().getResource("/media/fondo.wav");
            pw1 = new PlayWave(url);
            pw1.start();
        } catch (URISyntaxException e) {
            System.out.println("Error en la URL");
        }
    }
    
    public void juegoInicio() {
        banInicio = false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcercaDe;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImagen1;
    private javax.swing.JLabel lblImagen2;
    private javax.swing.JLabel lblImagen3;
    private javax.swing.JLabel lblImagen4;
    private javax.swing.JLabel lblImagen5;
    private javax.swing.JLabel lblImagen6;
    private javax.swing.JLabel lblImagen7;
    private javax.swing.JLabel lblImagen8;
    private javax.swing.JLabel lblImagen9;
    private javax.swing.JLabel lblTirador;
    // End of variables declaration//GEN-END:variables
}
